import type { PromptRecipe } from '../types';

const SEED_PROMPTS: Omit<PromptRecipe, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    workspaceId: 'local',
    title: 'Summarize Text',
    description: 'Condense any text into a clear summary',
    body: 'Please summarize the following text in {{length}} sentences:\n\n{{text}}',
    tags: ['writing', 'summary'],
    folderId: null,
    favorite: true,
    archived: false,
    archivedAt: null,
    lastUsedAt: null,
    createdBy: 'local',
    version: 1,
  },
  {
    workspaceId: 'local',
    title: 'Rewrite in Clear English',
    description: 'Simplify complex text for clarity',
    body: 'Rewrite the following text in clear, simple English at a {{reading_level}} reading level:\n\n{{text}}',
    tags: ['writing', 'clarity'],
    folderId: null,
    favorite: false,
    archived: false,
    archivedAt: null,
    lastUsedAt: null,
    createdBy: 'local',
    version: 1,
  },
  {
    workspaceId: 'local',
    title: 'Generate Product Ideas',
    description: 'Brainstorm product ideas for a given market',
    body: 'Generate {{count}} product ideas for the {{market}} market. For each idea, include:\n- Product name\n- One-line description\n- Target audience\n- Key differentiator',
    tags: ['brainstorm', 'product'],
    folderId: null,
    favorite: false,
    archived: false,
    archivedAt: null,
    lastUsedAt: null,
    createdBy: 'local',
    version: 1,
  },
  {
    workspaceId: 'local',
    title: 'Code Review Assistant',
    description: 'Get a thorough code review',
    body: 'Review the following {{language}} code. Focus on:\n1. Bugs and potential issues\n2. Performance improvements\n3. Readability and best practices\n\n```{{language}}\n{{code}}\n```',
    tags: ['code', 'review'],
    folderId: null,
    favorite: true,
    archived: false,
    archivedAt: null,
    lastUsedAt: null,
    createdBy: 'local',
    version: 1,
  },
  {
    workspaceId: 'local',
    title: 'Email Draft',
    description: 'Draft a professional email',
    body: 'Draft a {{tone}} email to {{recipient}} about {{subject}}.\n\nKey points to include:\n{{key_points}}',
    tags: ['email', 'communication'],
    folderId: null,
    favorite: false,
    archived: false,
    archivedAt: null,
    lastUsedAt: null,
    createdBy: 'local',
    version: 1,
  },
  {
    workspaceId: 'local',
    title: 'Meeting Notes Extractor',
    description: 'Extract action items from meeting notes',
    body: 'From the following meeting notes, extract:\n1. Key decisions made\n2. Action items with owners\n3. Follow-up dates\n\nMeeting: {{meeting_title}}\nDate: {{date}}\n\nNotes:\n{{notes}}',
    tags: ['meetings', 'productivity'],
    folderId: null,
    favorite: false,
    archived: false,
    archivedAt: null,
    lastUsedAt: null,
    createdBy: 'local',
    version: 1,
  },
];

export function getSeedPrompts(): Omit<PromptRecipe, 'id' | 'createdAt' | 'updatedAt'>[] {
  return SEED_PROMPTS;
}
